name: 'Zip Dist Folders'
author: 'KivySwiftLink'
description: 'Zips all dist folders'

runs:
  using: "composite"
  steps:
    - name: python_dist.zip
      shell: bash
      working-directory: output/python3
      run: |
        zip -r python_dist.zip dist
        rm -rf dist

    - name: kivy_dist.zip
      shell: bash
      working-directory: output/kivy
      run: |
        zip -r kivy_dist.zip dist
        rm -rf dist
        zip -r site-packages.zip site-packages
        rm -rf site-packages
    
    - name: numpy_dist.zip
      shell: bash
      working-directory: ./output/numpy
      run: |
        zip -r numpy_dist.zip dist
        rm -rf dist
        zip -r site-packages.zip site-packages
        rm -rf site-packages

    - name: pillow_dist.zip
      shell: bash
      working-directory: ./output/pillow
      run: |
        zip -r pillow_dist.zip dist
        rm -rf dist
        zip -r pillow_site.zip site-packages
        rm -rf site-packages

    - name: kiwisolver_dist.zip
      shell: bash
      working-directory: ./output/kiwisolver
      run: |
        zip -r kiwisolver_dist.zip dist
        rm -rf dist
        zip -r kiwisolver_site.zip site-packages
        rm -rf site-packages

    - name: matplotlib_dist.zip
      shell: bash
      working-directory: ./output/matplotlib
      run: |
        zip -r matplotlib_dist.zip dist
        rm -rf dist
        zip -r matplotlib_site.zip site-packages
        rm -rf site-packages

    - name: materialyoucolor_dist.zip
      shell: bash
      working-directory: ./output/materialyoucolor
      run: |
        zip -r materialyoucolor_dist.zip dist
        rm -rf dist
        zip -r materialyoucolor_site.zip site-packages
        rm -rf site-packages

    - name: ffmpeg_dist.zip
      shell: bash
      working-directory: ./output/ffmpeg
      run: |
        zip -r ffmpeg_dist.zip dist
        rm -rf dist

    - name: ffpyplayer_dist.zip
      shell: bash
      working-directory: ./output/ffpyplayer
      run: |
        zip -r ffpyplayer_dist.zip dist
        rm -rf dist
        zip -r ffpyplayer_site.zip site-packages
        rm -rf site-packages