name: 'Install Kivy-ios'
author: 'PythonSwiftLink'
description: 'Set up your GitHub Actions workflow with a specific version of Xcode'

runs:
  using: "composite"
  steps:
    - name: install kivy-ios
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        git clone https://github.com/kivyswiftlink/kivy-ios
        pip3 install -e kivy-ios
          
          
